'use strict';
SI.factory('couponMokeService', function (
	$window, 
	$http, 
	$q, 
	$timeout,
    $ionicLoading, 
    $state, 
    siConfig,
    NativeService
    ) {
	var getcoupon = {
		body:[
			{
				Amount:"80",
				NeedMoney:"200",
				couponStyle:"诊间支付券",
				code:"1",
				couponDate:"2016.08.01-2016.08.21",
				con:[
					{
						leftCon:"·可与其它优惠券同时使用",
						rightCon:"·仅深圳用户使用"
					},
					{
						leftCon:"·仅支持诊间在线支付抵扣",
						rightCon:".dasdasdas"
					}
				]
			},
			{
				Amount:"20",
				NeedMoney:"100",
				couponStyle:"预约挂号券",
				code:"2",
				couponDate:"2016.08.01-2016.08.21",
				con:[
					{
						leftCon:"·可与其它优惠券同时使用",
						rightCon:"·仅深圳用户使用"
					},
					{
						leftCon:"·仅支持诊间在线支付抵扣",
						rightCon:""
					}
				]
			},			{
				Amount:"80",
				NeedMoney:"200",
				couponStyle:"诊间支付券",
				couponDate:"2016.08.01-2016.08.21",
				con:[
					{
						leftCon:"·可与其它优惠券同时使用",
						rightCon:"·仅深圳用户使用"
					},
					{
						leftCon:"·仅支持诊间在线支付抵扣",
						rightCon:""
					}
				]
			},
			{
				Amount:"20",
				NeedMoney:"100",
				couponStyle:"预约挂号券",
				couponDate:"2016.08.01-2016.08.21",
				con:[
					{
						leftCon:"·可与其它优惠券同时使用",
						rightCon:"·仅深圳用户使用"
					},
					{
						leftCon:"·仅支持诊间在线支付抵扣",
						rightCon:""
					}
				]
			},			{
				Amount:"80",
				NeedMoney:"200",
				couponStyle:"诊间支付券",
				couponDate:"2016.08.01-2016.08.21",
				con:[
					{
						leftCon:"·可与其它优惠券同时使用",
						rightCon:"·仅深圳用户使用"
					},
					{
						leftCon:"·仅支持诊间在线支付抵扣",
						rightCon:""
					}
				]
			},
			{
				Amount:"20",
				NeedMoney:"100",
				couponStyle:"预约挂号券",
				couponDate:"2016.08.01-2016.08.21",
				con:[
					{
						leftCon:"·可与其它优惠券同时使用",
						rightCon:"·仅深圳用户使用"
					},
					{
						leftCon:"·仅支持诊间在线支付抵扣",
						rightCon:""
					}
				]
			},			{
				Amount:"80",
				NeedMoney:"200",
				couponStyle:"诊间支付券",
				couponDate:"2016.08.01-2016.08.21",
				con:[
					{
						leftCon:"·可与其它优惠券同时使用",
						rightCon:"·仅深圳用户使用"
					},
					{
						leftCon:"·仅支持诊间在线支付抵扣",
						rightCon:""
					}
				]
			},
			{
				Amount:"20",
				NeedMoney:"100",
				couponStyle:"预约挂号券",
				couponDate:"2016.08.01-2016.08.21",
				con:[
					{
						leftCon:"·可与其它优惠券同时使用",
						rightCon:"·仅深圳用户使用"
					},
					{
						leftCon:"·仅支持诊间在线支付抵扣",
						rightCon:""
					}
				]
			},			{
				Amount:"80",
				NeedMoney:"200",
				couponStyle:"诊间支付券",
				couponDate:"2016.08.01-2016.08.21",
				con:[
					{
						leftCon:"·可与其它优惠券同时使用",
						rightCon:"·仅深圳用户使用"
					},
					{
						leftCon:"·仅支持诊间在线支付抵扣",
						rightCon:""
					}
				]
			},
			{
				Amount:"20",
				NeedMoney:"100",
				couponStyle:"预约挂号券",
				couponDate:"2016.08.01-2016.08.21",
				con:[
					{
						leftCon:"·可与其它优惠券同时使用",
						rightCon:"·仅深圳用户使用"
					},
					{
						leftCon:"·仅支持诊间在线支付抵扣",
						rightCon:""
					}
				]
			},			{
				Amount:"80",
				NeedMoney:"200",
				couponStyle:"诊间支付券",
				couponDate:"2016.08.01-2016.08.21",
				con:[
					{
						leftCon:"·可与其它优惠券同时使用",
						rightCon:"·仅深圳用户使用"
					},
					{
						leftCon:"·仅支持诊间在线支付抵扣",
						rightCon:""
					}
				]
			},
			{
				Amount:"20",
				NeedMoney:"100",
				couponStyle:"预约挂号券",
				couponDate:"2016.08.01-2016.08.21",
				con:[
					{
						leftCon:"·可与其它优惠券同时使用",
						rightCon:"·仅深圳用户使用"
					},
					{
						leftCon:"·仅支持诊间在线支付抵扣",
						rightCon:""
					}
				]
			}
		]
	}

	return {
		getcoupon:function(){
			return getcoupon
		}
	}
})
    